name: Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: yarn install
      
    - name: Build project
      run: yarn build
      
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1
      with:
        host: 117.72.10.253
        username: lupeng
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/lupeng/webapp
          git pull origin main
          yarn install --production
          pm2 restart all